version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pro-dj-postgres-dev
    environment:
      POSTGRES_DB: pro_dj_dev
      POSTGRES_USER: pro_dj_user
      POSTGRES_PASSWORD: pro_dj_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - pro-dj-network-dev

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: pro-dj-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - pro-dj-network-dev

  # Pro-DJ Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pro-dj-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://pro_dj_user:pro_dj_password@postgres:5432/pro_dj_dev
      - REDIS_URL=redis://redis:6379
      - NODE_OPTIONS=--max-old-space-size=4096
      # Add your other environment variables here
      # - AWS_ACCESS_KEY_ID=your_aws_key
      # - AWS_SECRET_ACCESS_KEY=your_aws_secret
      # - AWS_REGION=your_aws_region
      # - AWS_S3_BUCKET=your_s3_bucket
      # - NEXTAUTH_SECRET=your_nextauth_secret
      # - NEXTAUTH_URL=http://localhost:3000
      # - STRIPE_SECRET_KEY=your_stripe_secret
      # - STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret
      # - RESEND_API_KEY=your_resend_key
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./uploads:/app/public/uploads
    networks:
      - pro-dj-network-dev
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: sh -c "npx prisma migrate deploy && npm run dev"

  # Prisma Studio (Database Management)
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pro-dj-prisma-studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://pro_dj_user:pro_dj_password@postgres:5432/pro_dj_dev
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pro-dj-network-dev
    command: npx prisma studio --hostname 0.0.0.0 --port 5555

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  pro-dj-network-dev:
    driver: bridge
